### ISSUE TITLE
address read from dwarf is not absolute

### ISSUE THREAD

**Issue by 9chu** [TartanLlama/minidbg#6]
Thank you for your good tutorial!

But I can't make a breakpoint on a simple function following the code.
It seems dwarf++ read a relative PC offset, which begins from 0x0000000, thus I cannot write INT 3 on it.

How can I solve it?

**Comment by TartanLlama** [comment]
Hi! It seems I need to update my posts and code for position-independent executables. 

In the mean time, you have two options:

1. Compile your test programs with `-fno-pie` so they are not position-independent
2. Offset your PC-relative addresses by the load address of the executable, which you can find in /proc/<pid\>/maps

**Comment by 9chu** [comment]
Thanks!
I'm trying to read the base address from /proc/.../maps.
